## Домашнаяя работа №1
### Тема: настройка рабочей среды, работа с Git, структура репозитория и базовые операции в NumPy

#### 1. Импорт библиотеки `NumPy`, создание массивов и демонстрация их атрибутов
Импортируем библиотеку NumPy и сократим его имя: `import numpy as np`

In [149]:
import numpy as np

Создадим массивы из обычных списков и выведем на экран их размер и содержимое

In [150]:
row = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) # превращает список значений в NumPy массив

print("Размер row:", row.shape)
print("Тип данных внутри row:", row.dtype)
print("Значения row:\n",row)

Размер row: (9,)
Тип данных внутри row: int64
Значения row:
 [1 2 3 4 5 6 7 8 9]


Создадим массив с помощью `np.arange()` и выведем его размер и содержимое

In [151]:
array = np.arange(10, 20, 0.5) # start=0, stop, step=1, dtype

print("Размер array:", array.shape)
print("Тип данных внутри array:", array.dtype)
print("Значения array:\n", array)

Размер array: (20,)
Тип данных внутри array: float64
Значения array:
 [10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5]


Создадим массивы с помощью `zeros`, `ones`

In [152]:
onesMatrix = np.ones(shape=(3, 4)) # <=> np.ones((3, 4)) <- массив единиц размера shape
zerosTensor = np.zeros(shape=(2, 2, 2)) # массив нулей размера shape


print("\Размер onesMatrix:", onesMatrix.shape)
print("Тип данных внутри onesMatrix:", onesMatrix.dtype)
print("Значения onesMatrix:\n", onesMatrix)

print("\Размер zerosTensor:", zerosTensor.shape)
print("Тип данных внутри zerosTensor:", zerosTensor.dtype)
print("Значения zerosTensor:\n", zerosTensor)

\Размер onesMatrix: (3, 4)
Тип данных внутри onesMatrix: float64
Значения onesMatrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
\Размер zerosTensor: (2, 2, 2)
Тип данных внутри zerosTensor: float64
Значения zerosTensor:
 [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


Создадим массивымощью `empty`, `eye`

In [153]:
emptyTrashMatrix = np.empty(shape=(3, 3)) # заполняет матрицу размера 3x3 мусорными значениями
diagonalOnesMatrix = np.eye(3) # 3x3 диагональная матрица единиц


print("\Размер emptyTrashMatrix:", emptyTrashMatrix.shape)
print("Тип данных внутри emptyTrashMatrix:", emptyTrashMatrix.dtype)
print("Значения emptyTrashMatrix:\n", emptyTrashMatrix)

print("\Размер diagonalOnesMatrix:", diagonalOnesMatrix.shape)
print("Тип данных внутри diagonalOnesMatrix:", diagonalOnesMatrix.dtype)
print("Значения diagonalOnesMatrix:\n", diagonalOnesMatrix)

\Размер emptyTrashMatrix: (3, 3)
Тип данных внутри emptyTrashMatrix: float64
Значения emptyTrashMatrix:
 [[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]]
\Размер diagonalOnesMatrix: (3, 3)
Тип данных внутри diagonalOnesMatrix: float64
Значения diagonalOnesMatrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 2. Индексирование и срезы массивов `NumPy`
Рассмотрим индексирование и срезы вектор-строк (массивов размерностью 1: `row`, `array`)

In [154]:
print(f"Первый элемент row = {row[0]}; последний элемент row = {row[-1]}\n" +
      f"Первый элемент array = {array[0]}; последний элемент array = {array[-1]}")
print(f"Срез всех элементов с четными индексами. row: {row[::2]} \narray: {array[::2]}")

Первый элемент row = 1; последний элемент row = 9
Первый элемент array = 10.0; последний элемент array = 19.5
Срез всех элементов с четными индексами. row: [1 3 5 7 9] 
array: [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]


Создадим массив случайных целых чисел размером 3x3 в диапазоне от 0 до 100

In [155]:
randomMatrix = np.random.randint(0, 50, (3, 3))

print("Исходный массив:\n", randomMatrix)
print("3-й элемент 2-й строки:", randomMatrix[1][2])
print("3-я строка в обратном порядке:", randomMatrix[2][::-1])
# [x][y] эквивалентно [x, y] в массивах NumPy
# Обращение [x, y] эффективнее стандартного [x][y], так как требуется меньше операций для интерпретатора
print("3-я строка в обратном порядке (без создания копии):", randomMatrix[2, ::-1])

np.random.shuffle(randomMatrix)
print("shuffle перемешивает элементы массива:\n", randomMatrix)

Исходный массив:
 [[29 48 11]
 [34 40 34]
 [27 39 44]]
3-й элемент 2-й строки: 34
3-я строка в обратном порядке: [44 39 27]
3-я строка в обратном порядке (без создания копии): [44 39 27]
shuffle перемешивает элементы массива:
 [[34 40 34]
 [29 48 11]
 [27 39 44]]


#### 3. Операции над массивами и примеры базовых статистик
Выполним сложение матрицы из нулей и некоторого целого числа

In [156]:
print("Тензор из нулей:\n", zerosTensor)
print("Тензор из нулей с прибавленным значением 10:\n", zerosTensor + 10) 
# Сложение скаляра(целого числа) и массива NumPy производит поэлементное сложение

Тензор из нулей:
 [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
Тензор из нулей с прибавленным значением 10:
 [[[10. 10.]
  [10. 10.]]

 [[10. 10.]
  [10. 10.]]]


Создадим некоторый массив (вектор-строку) с помощью row, выполним поворот и их произведение

In [157]:
column = (row + 5).transpose() # transpose не работает для одномерных массивов
column = column.reshape(9, 1)
print("Значения column:\n", column)
print("Значения row:\n", row)
print("Матрица их произведения:\n", row*column) # НЕ матричное умножение

Значения column:
 [[ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]]
Значения row:
 [1 2 3 4 5 6 7 8 9]
Матрица их произведения:
 [[  6  12  18  24  30  36  42  48  54]
 [  7  14  21  28  35  42  49  56  63]
 [  8  16  24  32  40  48  56  64  72]
 [  9  18  27  36  45  54  63  72  81]
 [ 10  20  30  40  50  60  70  80  90]
 [ 11  22  33  44  55  66  77  88  99]
 [ 12  24  36  48  60  72  84  96 108]
 [ 13  26  39  52  65  78  91 104 117]
 [ 14  28  42  56  70  84  98 112 126]]


Создадим массив размером 3x3 с помощью `np.random.randint` и выполним некоторые операции

In [158]:
secondRandomMatrix = np.random.randint(0, 100, (3, 3))
print("Значения secondRandomMatrix:\n", secondRandomMatrix, "\nЗначения randomMatrix:\n", randomMatrix)
print("Результат суммы двух матриц:\n", secondRandomMatrix + randomMatrix)
print("Результат разности двух матриц:\n", secondRandomMatrix - randomMatrix)
print("Результат произведения двух матриц:\n", secondRandomMatrix * randomMatrix)
print("Результат деления двух матриц:\n", secondRandomMatrix / randomMatrix)

Значения secondRandomMatrix:
 [[24 20 33]
 [47 58 93]
 [18 19 10]] 
Значения randomMatrix:
 [[34 40 34]
 [29 48 11]
 [27 39 44]]
Результат суммы двух матриц:
 [[ 58  60  67]
 [ 76 106 104]
 [ 45  58  54]]
Результат разности двух матриц:
 [[-10 -20  -1]
 [ 18  10  82]
 [ -9 -20 -34]]
Результат произведения двух матриц:
 [[ 816  800 1122]
 [1363 2784 1023]
 [ 486  741  440]]
Результат деления двух матриц:
 [[0.70588235 0.5        0.97058824]
 [1.62068966 1.20833333 8.45454545]
 [0.66666667 0.48717949 0.22727273]]


Рассмотрим объединения и разбиения массивов

In [159]:
# Объединим две матрицы
comboMatrix = np.hstack((secondRandomMatrix, randomMatrix))  # Горизонтальное объединение -> дописывает справа столбцы (количество строк одинаково)
print("Горизонтальное объединение:\n", comboMatrix)
comboMatrix = np.vstack((secondRandomMatrix, randomMatrix))  # Вертикальное объединение -> дописывает строки снизу (количество столбцов одинаково)
print("Вертикальное объединение:\n", comboMatrix)

comboMatrix = np.vstack((secondRandomMatrix, np.random.randint(0, 100, (1, 3))))
print("Дополнение случайной строкой:\n",comboMatrix)
comboMatrix = np.hstack((secondRandomMatrix, np.random.randint(0, 100, (3, 1))))
print("Дополнение случайным столбцом:\n", comboMatrix)

Горизонтальное объединение:
 [[24 20 33 34 40 34]
 [47 58 93 29 48 11]
 [18 19 10 27 39 44]]
Вертикальное объединение:
 [[24 20 33]
 [47 58 93]
 [18 19 10]
 [34 40 34]
 [29 48 11]
 [27 39 44]]
Дополнение случайной строкой:
 [[24 20 33]
 [47 58 93]
 [18 19 10]
 [61 92 23]]
Дополнение случайным столбцом:
 [[24 20 33  6]
 [47 58 93 94]
 [18 19 10 86]]


Другие операции над матрицами

In [160]:
print("Рабочая матрица:\n", randomMatrix)

print("Транспонирование матрицы:\n", randomMatrix.transpose())  # Отражает матрицу относительно главной диагонали
print("Изменение формы:\n", randomMatrix.reshape(1, 9))  # Количество элементов не изменяется (может вызвать ошибку при неправильном изменении размера)
print("Сумма всех элементов массива:", randomMatrix.sum())
print(f"Миниальный элемент массива - {randomMatrix.min()}, максимальный элемент массива - {randomMatrix.max()}")
print(f"Среднее арифметическое матрицы - {randomMatrix.mean()}")
print("Вычисление функции косинуса от каждого элмента массива:\n", np.cos(randomMatrix))



Рабочая матрица:
 [[34 40 34]
 [29 48 11]
 [27 39 44]]
Транспонирование матрицы:
 [[34 29 27]
 [40 48 39]
 [34 11 44]]
Изменение формы:
 [[34 40 34 29 48 11 27 39 44]]
Сумма всех элементов массива: 306
Миниальный элемент массива - 11, максимальный элемент массива - 48
Среднее арифметическое матрицы - 34.0
Вычисление функции косинуса от каждого элмента массива:
 [[-0.84857027 -0.66693806 -0.84857027]
 [-0.74805753 -0.64014434  0.0044257 ]
 [-0.29213881  0.26664293  0.99984331]]
